#!/usr/bin/env python3
"""Regenerate config/endpoints.example.json from contracts/world-api.contract.json.

Every method+path pair in endpoints.example.json must exist in the contract;
ghost routes (routes the contract does not serve under that HTTP method) are
a D6 gate violation.  Run this script after the contract changes to keep the
two files in sync.

Usage:
  python3 scripts/gen-endpoints-example.py    # writes config/endpoints.example.json
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "world-api.contract.json"
OUTPUT = ROOT / "config" / "endpoints.example.json"


def main() -> None:
    contract = json.loads(CONTRACT.read_text())
    routes = contract["routes"]

    def select(plane: str) -> list[dict]:
        return [r for r in routes if r["plane"] == plane]

    def fmt(route: dict) -> str:
        return f"{route['method']}   {route['path']}"

    lifecycle_keys = [
        "challenge", "join", "actions", "sleep", "digest", "session",
    ]
    lifecycle_routes = {
        "challenge": next(
            (r for r in routes if "join/challenge" in r["path"] and r["method"] == "GET"), None),
        "join": next(
            (r for r in routes if r["path"].endswith("/join") and r["method"] == "POST"), None),
        "actions": next(
            (r for r in routes if "agents/:id/actions" in r["path"] and r["method"] == "POST"), None),
        "sleep": next(
            (r for r in routes if "agents/:id/sleep" in r["path"] and r["method"] == "POST"), None),
        "digest": next(
            (r for r in routes if "observations/digest" in r["path"] and r["method"] == "GET"), None),
        "session": next(
            (r for r in routes if "agents/:id/session" in r["path"] and r["method"] == "DELETE"), None),
    }

    spectator_routes = {
        r["path"].rsplit("/", 1)[-1].replace(":", "_").replace("/", "_"): f"{r['method']} {r['path']}"
        for r in select("spectator")
    }

    out = {
        "_comment": (
            "Generated by scripts/gen-endpoints-example.py from "
            f"contracts/world-api.contract.json ({contract['generated_from']}). "
            "Do not hand-edit — every method+path here is held to the contract by D6."
        ),
        "world": {
            "baseUrl": "https://world.lysvik.app",
            "lifecycle": {
                k: (f"{v['method']}   {v['path']}" if v else None)
                for k, v in lifecycle_routes.items()
            },
            "spectator": spectator_routes,
        },
        "agirails": {
            "sdk": "https://github.com/agirails/sdk-js",
            "docs": "https://github.com/agirails/docs",
            "chain": "Base",
            "identity": "ERC-8004",
            "settlement": "ACTP (on-chain USDC escrow, gasless via ERC-4337)",
        },
    }

    OUTPUT.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
